const NAMESPACE = "feqd"

export const API_GET_DECKS_REQUEST = `${NAMESPACE}/API_GET_DECKS_REQUEST`
export const API_GET_DECKS_SUCCESS = `${NAMESPACE}/API_GET_DECKS_SUCCESS`
export const API_GET_DECKS_FAILURE = `${NAMESPACE}/API_GET_DECKS_FAILURE`
